#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Debenhams.Resource", IsApplication=true)]

namespace Debenhams
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int action_menu = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btnminus = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ButtonStyle = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int date = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int debenhams = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int EditableTextStyle = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int EditTextStyle = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int LogoDebenhamsMenu = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int LogoLogOut = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int LogoReceiving = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int LogoStockTransferReceiving = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int LogoUser = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int passwordloginbutton = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int refresh = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int RSCI_APP_LOGO = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int RSCI_ORIGINAL = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int RSCI_ORIGINALStore = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int rscistore = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int searchbutton = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int shop = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int TextBorder = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int TextBorderBotton = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int TextBorderCurve = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int TextSmall = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int userloginbutton = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int warning = 2130837529;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060016
			public const int ActLeftDrawer = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int FlyOutContent = 2131099671;
			
			// aapt resource value: 0x7f06000c
			public const int FlyOutMenu = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int Layout1 = 2131099658;
			
			// aapt resource value: 0x7f060015
			public const int MenuLogout = 2131099669;
			
			// aapt resource value: 0x7f060010
			public const int MenuPilerName = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int MenuReceiving = 2131099666;
			
			// aapt resource value: 0x7f060027
			public const int TableLayout1 = 2131099687;
			
			// aapt resource value: 0x7f06001b
			public const int TableLayout2 = 2131099675;
			
			// aapt resource value: 0x7f060034
			public const int TableLayout3 = 2131099700;
			
			// aapt resource value: 0x7f060028
			public const int btnDone = 2131099688;
			
			// aapt resource value: 0x7f060036
			public const int btnEncodeUPC = 2131099702;
			
			// aapt resource value: 0x7f06001f
			public const int btnScanBox = 2131099679;
			
			// aapt resource value: 0x7f060035
			public const int btnScanUpc = 2131099701;
			
			// aapt resource value: 0x7f06003d
			public const int btnlogin = 2131099709;
			
			// aapt resource value: 0x7f060026
			public const int btnsearch = 2131099686;
			
			// aapt resource value: 0x7f060005
			public const int datepicker = 2131099653;
			
			// aapt resource value: 0x7f06003c
			public const int debenhams = 2131099708;
			
			// aapt resource value: 0x7f060018
			public const int frameLayout1 = 2131099672;
			
			// aapt resource value: 0x7f06003f
			public const int imageView1 = 2131099711;
			
			// aapt resource value: 0x7f060002
			public const int imgLogo = 2131099650;
			
			// aapt resource value: 0x7f06003b
			public const int imgbtnqtyminus = 2131099707;
			
			// aapt resource value: 0x7f06002e
			public const int lblBoxCode = 2131099694;
			
			// aapt resource value: 0x7f060022
			public const int lblLot = 2131099682;
			
			// aapt resource value: 0x7f060021
			public const int lblPO = 2131099681;
			
			// aapt resource value: 0x7f06001c
			public const int lblPo = 2131099676;
			
			// aapt resource value: 0x7f060037
			public const int lblQty = 2131099703;
			
			// aapt resource value: 0x7f06002c
			public const int lblSKU = 2131099692;
			
			// aapt resource value: 0x7f060032
			public const int lbldivision = 2131099698;
			
			// aapt resource value: 0x7f06002f
			public const int lblremark = 2131099695;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f06000d
			public const int linearLayout2 = 2131099661;
			
			// aapt resource value: 0x7f06003a
			public const int linearLayout3 = 2131099706;
			
			// aapt resource value: 0x7f060006
			public const int linearLayout7 = 2131099654;
			
			// aapt resource value: 0x7f06002d
			public const int lvBox = 2131099693;
			
			// aapt resource value: 0x7f060038
			public const int lvUpc = 2131099704;
			
			// aapt resource value: 0x7f060023
			public const int lvpo = 2131099683;
			
			// aapt resource value: 0x7f060019
			public const int menuHdrButton = 2131099673;
			
			// aapt resource value: 0x7f060040
			public const int myButton = 2131099712;
			
			// aapt resource value: 0x7f06000e
			public const int tableLayout1 = 2131099662;
			
			// aapt resource value: 0x7f060013
			public const int tableLayout3 = 2131099667;
			
			// aapt resource value: 0x7f06000f
			public const int tableRow1 = 2131099663;
			
			// aapt resource value: 0x7f060014
			public const int tableRow2 = 2131099668;
			
			// aapt resource value: 0x7f06002a
			public const int tableRow4 = 2131099690;
			
			// aapt resource value: 0x7f060007
			public const int textView1 = 2131099655;
			
			// aapt resource value: 0x7f06001a
			public const int textView2 = 2131099674;
			
			// aapt resource value: 0x7f06003e
			public const int txtPassword = 2131099710;
			
			// aapt resource value: 0x7f060020
			public const int txtScanBox = 2131099680;
			
			// aapt resource value: 0x7f06002b
			public const int txtScanUpc = 2131099691;
			
			// aapt resource value: 0x7f060004
			public const int txtUserName = 2131099652;
			
			// aapt resource value: 0x7f060033
			public const int txtbox_code = 2131099699;
			
			// aapt resource value: 0x7f060039
			public const int txtdescr = 2131099705;
			
			// aapt resource value: 0x7f060024
			public const int txtload = 2131099684;
			
			// aapt resource value: 0x7f06001d
			public const int txtload_code = 2131099677;
			
			// aapt resource value: 0x7f060029
			public const int txtloadnumber = 2131099689;
			
			// aapt resource value: 0x7f060031
			public const int txtmove_doc = 2131099697;
			
			// aapt resource value: 0x7f060003
			public const int txtpassword = 2131099651;
			
			// aapt resource value: 0x7f060009
			public const int txtqty = 2131099657;
			
			// aapt resource value: 0x7f06001e
			public const int txtsearch = 2131099678;
			
			// aapt resource value: 0x7f060025
			public const int txtstatus = 2131099685;
			
			// aapt resource value: 0x7f060008
			public const int txtupc = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int txturl = 2131099659;
			
			// aapt resource value: 0x7f060001
			public const int txtusername = 2131099649;
			
			// aapt resource value: 0x7f060030
			public const int view1 = 2131099696;
			
			// aapt resource value: 0x7f060011
			public const int view2 = 2131099665;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int LayInputCredential = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int LayInputDATE = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int LayInputUpc = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int LayInputURL = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int LayLeftDrawer = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int LayLoadList = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int LayLoadListBox = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int LayLoadListBoxs = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int LayLoadListC = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int LayLoadLists = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int LayLoadListsDetail = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int LayLoadListsDetails = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int LayLoadScanUpc = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int LayLoadScanUpcs = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int LayLogin = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int LayStart = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int Main = 2130968592;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int notavailable = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int search = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
